settings:
  title: '服务器与系统运行状态'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 60 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: '所有系统运行正常'
  notAllmonitorsOperational: '有系统正在宕机'
  monitorLabelOperational: '运行正常'
  monitorLabelNotOperational: '宕机'
  monitorLabelNoData: '无数据'
  dayInHistogramNoData: '无数据'
  dayInHistogramOperational: '全部正常'
  dayInHistogramNotOperational: ' 次意外' # xx 次意外 recorded

monitors:
  - id: workers-cloudflare-com # unique identifier
    name: workers.cloudflare.com
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://workers.cloudflare.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: hanbingverse.com
    name: 寒冰冽
    description: '屑寒个人网站'
    url: 'https://hanbingverse.com/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: inter-knot.com
    name: 绳网
    description: '绝区零玩家二创绳网'
    url: 'https://inter-knot.com/'
    method: GET
    expectStatus: 302
    linkable: true # allows the title to be a link, default=true

  - id: www.cloudflare.com
    name: cloudflare
    description: 'Connect, protect and build everywhere'
    url: 'https://www.cloudflare.com/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: cloud.tencent.com
    name: Cloud.Tencent
    description: '腾讯云'
    url: 'https://cloud.tencent.com/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: cn.aliyun.com
    name: 阿里云
    description: '阿里云'
    url: 'https://cn.aliyun.com/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: uptimerobot
    name: 监测站二号
    description: '备用监测站点'
    url: 'https://status.hanbingverse.com/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
